<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuite_DataDriven</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>7</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>87b0e326-c369-4313-809f-afdec8147cff</testSuiteGuid>
   <testCaseLink>
      <guid>3a6117f6-c129-4842-a658-82a6d571b33f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day3/DataDriven</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>72622a4e-db61-44f1-adc2-2a4c32e70420</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataOne</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>72622a4e-db61-44f1-adc2-2a4c32e70420</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>2d78c063-d320-4b97-8574-a3d2c66d9aca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>72622a4e-db61-44f1-adc2-2a4c32e70420</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>5a2b7902-8b0e-4d02-b3d0-4fdaf1a63cc4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
